// Action types for the Recipe Categories
export const GET_RECIPE_CATEGORIES = "GET_RECIPE_CATEGORIES";
export const GET_RECIPE_SUCCESS = "GET_RECIPE_SUCCESS";
export const GET_RECIPE_FAILURE = "GET_RECIPE_FAILURE";

// Action types for Category Details
export const GET_RECIPE_DISHES = "GET_RECIPE_DISHES";
export const GET_CATEGORY_DISHES_SUCCESS="GET_CATEGORY_DISHES_SUCCESS"
export const GET_CATEGORY_DISHES_FAILURE="GET_CATEGORY_DISHES_FAILURE"

// Action types for Detailed Recipe
export const GET_EACH_RECIPE = "GET_EACH_RECIPE";
export const GET_DETAILED_RECIPE_SUCCESS="GET_DETAILED_RECIPE_SUCCESS"
export const GET_DETAILED_RECIPE_FAILURE="GET_DETAILED_RECIPE_FAILURE"

